# Variable 'OnlinePassword' was defined in the Variables tab
resources:
  repositories:
  - repository: self
    type: git
    ref: master
jobs:
- job: Job_1
  displayName: Agent job 1
  pool:
    vmImage: windows-2019
  steps:
  - checkout: self
    clean: true
    fetchTags: false
  - task: PowerShell@2
    displayName: Establecer pantalla del agente Resolución a 1920 x 1080
    inputs:
      targetType: inline
      script: "# Set agent screen resolution to 1920x1080 to avoid sizing issues with Portal  \nSet-DisplayResolution -Width 1920 -Height 1080 -Force\n# Wait 10 seconds  \nStart-Sleep -s 10\n# Verify Screen Resolution is set to 1920x1080  \nGet-DisplayResolution"
  - task: NuGetCommand@2
    displayName: Restore NuGet Packages
    inputs:
      solution: PowerAppsTestAutomation.sln
  - task: VSBuild@1
    displayName: Build Power Apps Test Automation Solution
    inputs:
      solution: PowerAppsTestAutomation.sln
  - task: VSTest@2
    displayName: ' Run Power Apps Test Automation Tests via $(BrowserTypeChrome)'
    inputs:
      testAssemblyVer2: '**\Microsoft.PowerApps.TestAutomation.Tests\bin\\Debug\Microsoft.PowerApps.TestAutomation.Tests.dll'
      testFiltercriteria: TestCategory=PowerAppsTestAutomation
      uiTests: true
      runSettingsFile: Microsoft.PowerApps.TestAutomation.Tests/patestautomation.runsettings
      overrideTestrunParameters: -OnlineUsername "$(OnlineUsername)" -OnlinePassword "$(OnlinePassword)" -BrowserType "$(BrowserTypeChrome)" -OnlineUrl "$(OnlineUrl)" -UsePrivateMode "$(UsePrivateMode)" -TestAutomationURLFilePath "$(TestAutomationURLFilePath)" -DriversPath "$(ChromeWebDriver)"
      testRunTitle: Run Power Apps Test Automation Tests via $(BrowserTypeChrome)
  - task: VSTest@2
    displayName: Run Power Apps Test Automation Tests via $(BrowserTypeFirefox)
    inputs:
      testAssemblyVer2: '**\Microsoft.PowerApps.TestAutomation.Tests\bin\\Debug\Microsoft.PowerApps.TestAutomation.Tests.dll'
      testFiltercriteria: TestCategory=PowerAppsTestAutomation
      uiTests: true
      runSettingsFile: Microsoft.PowerApps.TestAutomation.Tests/patestautomation.runsettings
      overrideTestrunParameters: -OnlineUsername "$(OnlineUsername)" -OnlinePassword "$(OnlinePassword)" -BrowserType "$(BrowserTypeFirefox)" -OnlineUrl "$(OnlineUrl)" -UsePrivateMode "$(UsePrivateMode)" -TestAutomationURLFilePath "$(TestAutomationURLFilePath)" -DriversPath "$(GeckoWebDriver)"
      testRunTitle: Run Power Apps Test Automation Tests via $(BrowserTypeFirefox)
...
